import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const company = { name:'RAPID AIR LIMITED', email:'RAPIDAIRLIMITED@outlook.com', address:'122-126 Guangdong Road, Tsim Sha Tsui, Yau Tsim Mong District, Hong Kong Special Administrative Region' }
const imagePool = [
  'photo-1616486338812-3dadae4b4ace','photo-1600566753190-17f0baa2a6c3','photo-1618221195710-dd6b41faaea6','photo-1615874694520-474822394e73','photo-1556228720-195a672e8a03','photo-1586023492125-27b2c045efd7','photo-1617104678098-de229db51175','photo-1524758631624-e2822e304c36','photo-1555041469-a586c61ea9bc','photo-1505693416388-ac5ce068fe85','photo-1519710164239-da123dc03ef4','photo-1493663284031-b7e3aefcae8e','photo-1540932239986-30128078f3c5','photo-1598300042247-d088f8ab3a91','photo-1513506003901-1e6a229e2d15','photo-1494438639946-1ebd1d20bf85','photo-1513694203232-719a280e022f','photo-1517705008128-361805f42e86','photo-1505691938895-1758d7feb511','photo-1518005020951-eccb494ad742']
const categories = [
  { name:'Furniture', icon:'⌂', blurb:'Anchoring pieces for rooms that feel like home.', items:['Linen Sofa','Platform Bed','Oak Wardrobe','Solid Wood Dining Table','Round Coffee Table','Modern Bar Cabinet','Low Storage Cabinet','Outdoor Table & Chairs','Folding Guest Bed'] },
  { name:'Soft Furnishings', icon:'▱', blurb:'Layered textures that soften the everyday.', items:['Linen Curtains','Wool Area Rug','Boucle Throw Pillow','Framed Wall Art','Indoor Green Plant','Sheer Voile Curtains','Wooden Venetian Blinds','Textured Wallcovering','Handwoven Tapestry','Lumbar Cushion','Seat Cushion','Faux Floral Arrangement','Rattan Room Divider'] },
  { name:'Home Essentials', icon:'⌁', blurb:'Useful staples for restful, organized living.', items:['Four-Piece Bedding Set','Waffle Hand Towel','Stackable Storage Box','Linen Floor Mat','Cloud Cotton Quilt','Down Alternative Pillow','Stretch Bed Sheet','Spa Bath Towel','Lounge Bathrobe','Foldable Laundry Basket','Clear Storage Organizer','Canvas Storage Bag','Wooden Hanger Set','Garment Dust Cover','Linen Tissue Box','Home Slippers'] },
  { name:'Decor & Lighting', icon:'✦', blurb:'Quiet details that make a room feel personal.', items:['Ribbed Ceramic Vase','Handcrafted Object','Amber Reed Diffuser','Soft Glow Table Lamp','Arc Floor Lamp','Opal Wall Light','Minimal Desk Clock','Rounded Accent Mirror','Brass Candle Holder','Abstract Sculpture','Brass Wind Chime','Glass Display Vessel'] },
  { name:'Dining & Kitchen', icon:'◌', blurb:'Simple forms for slow meals and daily rituals.', items:['Stoneware Dinnerware Set','Everyday Coffee Cup','Woven Placemat Set','Washed Linen Tablecloth','Cork Trivet Set','Sculptural Fruit Bowl','Ceramic Spice Jar Set','Oak Kitchen Rack','Minimal Electric Kettle'] },
  { name:'Bathroom', icon:'◒', blurb:'Calm, practical essentials for a fresh start.', items:['Textured Shower Curtain','Cushioned Bath Mat','Brushed Towel Rail','Wall Bathroom Shelf','Vanity Organizer'] }
]
const generatedAssetNames = ['Linen Sofa','Platform Bed','Oak Wardrobe','Solid Wood Dining Table','Round Coffee Table','Modern Bar Cabinet','Low Storage Cabinet','Outdoor Table & Chairs','Folding Guest Bed','Linen Curtains','Wool Area Rug','Boucle Throw Pillow','Framed Wall Art','Indoor Green Plant','Sheer Voile Curtains','Wooden Venetian Blinds','Textured Wallcovering','Handwoven Tapestry','Seat Cushion','Lumbar Cushion','Faux Floral Arrangement','Rattan Room Divider','Four-Piece Bedding Set','Waffle Hand Towel','Stackable Storage Box','Linen Floor Mat','Cloud Cotton Quilt','Down Alternative Pillow','Stretch Bed Sheet','Spa Bath Towel','Lounge Bathrobe','Foldable Laundry Basket','Clear Storage Organizer','Wooden Hanger Set','Garment Dust Cover','Linen Tissue Box','Ribbed Ceramic Vase','Handcrafted Object','Amber Reed Diffuser','Soft Glow Table Lamp','Arc Floor Lamp','Opal Wall Light','Minimal Desk Clock','Rounded Accent Mirror','Brass Candle Holder','Abstract Sculpture','Brass Wind Chime','Glass Display Vessel','Stoneware Dinnerware Set','Everyday Coffee Cup','Woven Placemat Set','Washed Linen Tablecloth','Cork Trivet Set','Ceramic Spice Jar Set','Oak Kitchen Rack','Textured Shower Curtain','Cushioned Bath Mat','Brushed Towel Rail','Wall Bathroom Shelf','Vanity Organizer']
const generatedAssets = Object.fromEntries(generatedAssetNames.map((name, index) => [name, `/images/products/generated-${String(index + 1).padStart(2, '0')}.png`]))
generatedAssets['Minimal Electric Kettle'] = '/images/products/kettle.png'
generatedAssets['Canvas Storage Bag'] = '/images/products/canvas-storage-bag.png'
generatedAssets['Home Slippers'] = '/images/products/home-slippers.png'
generatedAssets['Sculptural Fruit Bowl'] = '/images/products/sculptural-fruit-bowl.png'
generatedAssets['Textured Shower Curtain'] = '/images/products/textured-shower-curtain.png'
generatedAssets['Cushioned Bath Mat'] = '/images/products/cushioned-bath-mat.png'
generatedAssets['Brushed Towel Rail'] = '/images/products/brushed-towel-rail.png'
generatedAssets['Wall Bathroom Shelf'] = '/images/products/wall-bathroom-shelf.png'
generatedAssets['Vanity Organizer'] = '/images/products/vanity-organizer.png'
generatedAssets['Stoneware Dinnerware Set'] = '/images/products/stoneware-dinnerware-set.png'
generatedAssets['Everyday Coffee Cup'] = '/images/products/everyday-coffee-cup.png'
generatedAssets['Woven Placemat Set'] = '/images/products/woven-placemat-set.png'
generatedAssets['Washed Linen Tablecloth'] = '/images/products/washed-linen-tablecloth.png'
generatedAssets['Minimal Desk Clock'] = '/images/products/minimal-desk-clock.png'
generatedAssets['Rounded Accent Mirror'] = '/images/products/rounded-accent-mirror.png'
generatedAssets['Brass Wind Chime'] = '/images/products/brass-wind-chime.png'
generatedAssets['Glass Display Vessel'] = '/images/products/glass-display-vessel.png'
generatedAssets['Ribbed Ceramic Vase'] = '/images/products/ribbed-ceramic-vase.png'
generatedAssets['Handcrafted Object'] = '/images/products/handcrafted-object.png'
generatedAssets['Amber Reed Diffuser'] = '/images/products/amber-reed-diffuser.png'
generatedAssets['Soft Glow Table Lamp'] = '/images/products/soft-glow-table-lamp.png'
generatedAssets['Arc Floor Lamp'] = '/images/products/arc-floor-lamp.png'
generatedAssets['Opal Wall Light'] = '/images/products/opal-wall-light.png'
generatedAssets['Brass Candle Holder'] = '/images/products/brass-candle-holder.png'
generatedAssets['Abstract Sculpture'] = '/images/products/abstract-sculpture.png'
generatedAssets['Ceramic Spice Jar Set'] = '/images/products/ceramic-spice-jar-set.png'
generatedAssets['Oak Kitchen Rack'] = '/images/products/oak-kitchen-rack.png'
const priceOverrides = { 'Ceramic Spice Jar Set':49, 'Oak Kitchen Rack':89 }
const products = categories.flatMap((cat, ci) => cat.items.map((name, i) => {
  return { id:`${ci}-${i}`, name, category:cat.name, price:priceOverrides[name] ?? (20 + ((ci*31+i*17)%281)), image:generatedAssets[name], description:`A considered ${name.toLowerCase()} designed for calm, practical everyday living.` }
}))
const terms = ['Agreement to Terms','Eligibility','Product Information','Orders and Acceptance','Pricing and Payment','Payment Security','Shipping and Delivery','Inspection on Arrival','Returns and Refunds','Cancellations','Product Care','Intellectual Property','User Content','Prohibited Uses','Disclaimer of Warranties','Limitation of Liability','Governing Law and Contact']

function App(){
  const [route,setRoute]=useState(location.hash.replace('#','')||'home'); const [cart,setCart]=useState([]); const [drawer,setDrawer]=useState(false); const [query,setQuery]=useState(''); const [category,setCategory]=useState('All');
  useEffect(()=>{const onHash=()=>setRoute(location.hash.replace('#','')||'home'); window.addEventListener('hashchange',onHash); return()=>window.removeEventListener('hashchange',onHash)},[])
  const go = r => { setRoute(r); location.hash=r; window.scrollTo({top:0,behavior:'smooth'}) }
  const add = (p, buy=false) => { setCart(c=>{ const found=c.find(x=>x.id===p.id); return found?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}] }); buy?go('checkout'):setDrawer(true) }
  const remove = id => setCart(c=>c.filter(x=>x.id!==id)); const total=cart.reduce((s,p)=>s+p.price*p.qty,0)
  const filtered=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase())),[category,query])
  return <>
    <Announcement/><Header cart={cart} onCart={()=>setDrawer(true)} onSearch={setQuery}/>
    {route==='home'&&<Home go={go} add={add}/>} {route==='shop'&&<Shop products={filtered} category={category} setCategory={setCategory} add={add}/>} {route==='checkout'&&<Checkout cart={cart} total={total} go={go}/>} {route==='admin'&&<Admin/>} {['about','shipping','tracking','service','privacy','dmca','returns','terms'].includes(route)&&<Info route={route}/>} 
    <Footer go={go}/><CartDrawer open={drawer} close={()=>setDrawer(false)} cart={cart} total={total} remove={remove} go={go}/>
  </>
}
function Announcement(){return <div className="announcement">Free delivery on orders over $80 <span>·</span> Thoughtful goods for everyday living</div>}
function Header({cart,onCart,onSearch}){return <header className="header"><div className="header-top"><button className="wordmark" onClick={()=>{location.hash='home';location.reload()}}>RAPID AIR</button><nav><button onClick={()=>location.hash='shop'}>Shop</button><button onClick={()=>location.hash='about'}>Our Story</button><button onClick={()=>location.hash='terms'}>Help & Legal</button></nav><div className="tools"><label className="search">⌕<input aria-label="Search products" placeholder="Search" onChange={e=>onSearch(e.target.value)}/></label><button className="cart-button" onClick={onCart}>Bag <span>{cart.reduce((s,p)=>s+p.qty,0)}</span></button></div></div></header>}
function Home({go,add}){return <main><section className="hero"><div className="hero-copy"><p className="eyebrow">A softer everyday</p><h1>Make room for<br/><em>good living.</em></h1><p className="hero-text">Home essentials, thoughtful decor and quiet comforts selected to bring ease to the spaces you live in.</p><button className="button dark" onClick={()=>go('shop')}>Explore the collection <span>→</span></button></div><div className="hero-art"><div className="art-circle"></div><div className="art-card art-one"></div><div className="art-card art-two"></div><div className="art-vase">◒</div></div></section><section className="intro"><p className="eyebrow">Shop by feeling</p><h2>Pieces with a place<br/>in your everyday.</h2><div className="category-grid">{categories.map(c=><button key={c.name} className="category-tile" onClick={()=>{go('shop')}}><span className="tile-icon">{c.icon}</span><span><b>{c.name}</b><small>{c.blurb}</small></span><i>↗</i></button>)}</div></section><section className="feature"><div className="feature-image"><div className="feature-lamp">◯</div></div><div className="feature-copy"><p className="eyebrow">The calm edit</p><h2>Small rituals,<br/>beautifully made.</h2><p>From a morning coffee to the last light of the evening, discover pieces that bring intention to the moments in between.</p><button className="button outline" onClick={()=>go('shop')}>Shop the edit</button></div></section><section className="home-products"><div className="section-head"><div><p className="eyebrow">Most loved</p><h2>Made for your space</h2></div><button className="text-link" onClick={()=>go('shop')}>View all <span>→</span></button></div><div className="product-grid">{products.slice(0,4).map(p=><ProductCard key={p.id} p={p} add={add}/>)}</div></section></main>}
function Shop({products,category,setCategory,add}){return <main className="shop-page"><div className="shop-heading"><p className="eyebrow">The collection</p><h1>Everything for<br/><em>good living.</em></h1><p>Explore our considered edit of home essentials, decor, lighting and everyday goods.</p></div><div className="filters"><button className={category==='All'?'active':''} onClick={()=>setCategory('All')}>All</button>{categories.map(c=><button className={category===c.name?'active':''} key={c.name} onClick={()=>setCategory(c.name)}>{c.name}</button>)}</div><p className="result-count">{products.length} pieces</p><div className="product-grid full">{products.map(p=><ProductCard key={p.id} p={p} add={add}/>)}</div></main>}
function ProductCard({p,add}){return <article className="product-card"><div className="product-image"><img src={p.image} alt={p.name}/><button className="quick" onClick={()=>add(p)}>Add to Cart</button></div><div className="product-meta"><div><h3>{p.name}</h3><p>{p.category}</p></div><strong>${p.price}</strong></div><button className="buy-now" onClick={()=>add(p,true)}>Buy Now — ${p.price}</button></article>}
function CartDrawer({open,close,cart,total,remove,go}){return <div className={`drawer-wrap ${open?'show':''}`}><div className="drawer-backdrop" onClick={close}></div><aside className="drawer"><div className="drawer-head"><h2>Your bag <span>{cart.reduce((s,p)=>s+p.qty,0)}</span></h2><button onClick={close}>×</button></div>{cart.length?<><div className="drawer-items">{cart.map(p=><div className="drawer-item" key={p.id}><img src={p.image} alt=""/><div><b>{p.name}</b><small>Qty {p.qty}</small><span>${p.price*p.qty}</span></div><button onClick={()=>remove(p.id)}>Remove</button></div>)}</div><div className="drawer-bottom"><div><span>Subtotal</span><b>${total}</b></div><button className="button dark wide" onClick={()=>{close();go('checkout')}}>Continue to checkout</button><small>Taxes and shipping calculated at checkout.</small></div></>:<div className="empty"><span>○</span><p>Your bag is waiting for something lovely.</p><button className="button outline" onClick={close}>Continue shopping</button></div>}</aside></div>}
function Checkout({cart,total,go}){const [paid,setPaid]=useState(false); const [method,setMethod]=useState('paypal'); return <main className="checkout"><div className="checkout-main"><p className="eyebrow">Secure checkout demo</p><h1>Almost <em>home.</em></h1>{paid?<div className="success"><span>✓</span><h2>Thank you for your order</h2><p>This front-end demo has recorded your payment preference. No real charge was made.</p><button className="button dark" onClick={()=>go('home')}>Back to home</button></div>:<><div className="steps"><span className="current">1. Details</span><span>2. Payment</span><span>3. Confirmation</span></div><div className="checkout-form"><label>Email address<input type="email" placeholder="you@example.com"/></label><div className="form-row"><label>First name<input placeholder="First name"/></label><label>Last name<input placeholder="Last name"/></label></div><label>Delivery address<input placeholder="Street address"/></label><div className="form-row"><label>City<input placeholder="City"/></label><label>Postal code<input placeholder="Postal code"/></label></div><h3>Payment method</h3><div className="payment-options">{[['paypal','PayPal'],['visa','Visa'],['card','Credit Card']].map(([key,label])=><button className={method===key?'selected':''} key={key} onClick={()=>setMethod(key)}><span className={`pay-icon ${key}`}>{key==='paypal'?'P':key==='visa'?'V':'▰'}</span>{label}<i>{method===key?'●':'○'}</i></button>)}</div><button className="button dark wide" disabled={!cart.length} onClick={()=>setPaid(true)}>Place demo order · ${total}</button><p className="small-note">By placing this order you agree to our Terms of Service and Privacy Policy. Payment processing is represented for demonstration only.</p></div></>}</div><aside className="order-summary"><h3>Order summary</h3>{cart.map(p=><div className="summary-item" key={p.id}><img src={p.image} alt=""/><span>{p.name}<small>Qty {p.qty}</small></span><b>${p.price*p.qty}</b></div>)}<div className="summary-total"><span>Total</span><strong>${total}</strong></div></aside></main>}
function Info({route}){const map={about:['About Rapid Air','We believe a well-considered home can make ordinary days feel a little better. RAPID AIR LIMITED curates useful, beautiful goods for living, resting and gathering.'],shipping:['Shipping Policy','Orders are prepared within 2–4 business days. Delivery estimates and any applicable fees are shown at checkout. Please contact us at RAPIDAIRLIMITED@outlook.com if your parcel needs help.'],tracking:['Order Tracking','For this front-end demonstration, order tracking is represented as a service page. A production version would connect this page to a carrier and order database.'],service:['Contact & Customer Care',company.email],privacy:['Privacy Policy','We only use information needed to support orders, customer care and site operations. We do not sell personal information. Contact us to request access, correction or deletion of your data.'],dmca:['DMCA','If you believe material on this site infringes your rights, please send a notice with the work, the location of the material and your contact details to RAPIDAIRLIMITED@outlook.com.'],returns:['Returns & Refunds','Request a return within 30 days of delivery. Items should be unused and in original condition. Approved refunds are sent to the original payment method after inspection.']}; if(route==='terms')return <main className="info-page"><p className="eyebrow">Legal</p><h1>Terms of <em>Service.</em></h1><p className="lead">Please read these terms before using the Rapid Air website.</p><div className="terms-list">{terms.map((t,i)=><section key={t}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{t}</h3><p>These terms describe how this part of our service works, the responsibilities of RAPID AIR LIMITED and the rights of customers using this website. Please contact us with questions.</p></div></section>)}</div></main>; const [title,text]=map[route]||map.about; return <main className="info-page"><p className="eyebrow">Rapid Air information</p><h1>{title}</h1><p className="lead">{text}</p><div className="info-card"><h3>RAPID AIR LIMITED</h3><p>{company.address}</p><p>{company.email}</p></div></main>}
function Admin(){const [ok,setOk]=useState(false); const [u,setU]=useState(''); const [p,setP]=useState(''); return <main className="admin-page">{!ok?<div className="admin-login"><p className="eyebrow">Staff portal</p><h1>Welcome <em>back.</em></h1><p>Sign in to the Rapid Air demo dashboard.</p><input placeholder="Username" value={u} onChange={e=>setU(e.target.value)}/><input placeholder="Password" type="password" value={p} onChange={e=>setP(e.target.value)}/><button className="button dark wide" onClick={()=>u==='admin'&&p==='RapidAir2026!'&&setOk(true)}>Sign in</button><small>Demo credentials: admin / RapidAir2026!</small></div>:<div className="dashboard"><p className="eyebrow">Dashboard</p><h1>Good morning, <em>team.</em></h1><div className="stats"><div><b>75</b><span>Products</span></div><div><b>5</b><span>Collections</span></div><div><b>$8,420</b><span>Demo revenue</span></div></div><div className="info-card"><h3>Store status</h3><p>All front-end modules are ready for review. Connect server-side authentication, inventory and a payment provider before launch.</p></div></div>}</main>}
function Footer({go}){return <footer><div className="footer-brand"><button className="wordmark" onClick={()=>go('home')}>RAPID AIR</button><p>Thoughtful goods for<br/>everyday living.</p><div className="social">◎ ◉ ◇</div></div><div className="footer-col"><h4>Shop</h4>{categories.map(c=><button key={c.name} onClick={()=>go('shop')}>{c.name}</button>)}</div><div className="footer-col"><h4>Customer care</h4>{[['about','About us'],['shipping','Shipping policy'],['tracking','Order tracking'],['returns','Returns & refunds'],['service','Contact us']].map(([r,l])=><button key={r} onClick={()=>go(r)}>{l}</button>)}</div><div className="footer-col"><h4>Legal</h4>{[['terms','Terms of Service'],['privacy','Privacy policy'],['dmca','DMCA']].map(([r,l])=><button key={r} onClick={()=>go(r)}>{l}</button>)}<button onClick={()=>go('admin')}>Staff login</button></div><div className="footer-contact"><h4>Company information</h4><p>{company.name}</p><p>{company.address}</p><a href={`mailto:${company.email}`}>{company.email}</a><div className="copyright">© 2026 RAPID AIR LIMITED</div></div></footer>}
createRoot(document.getElementById('root')).render(<App/>)
